- Home Server:
    - Pi-hole:
        icon: pi-hole.png
        href: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
        description: DNS sinkhole
    - Jellyfin:
        icon: jellyfin.png
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        description: Media server
    - Syncthing:
        icon: syncthing.png
        href: "{{HOMEPAGE_VAR_SYNCTHING_URL}}"
        description: File synchronization
