title: Home Server
theme: dark
color: slate
headerStyle: clean
layout:
  Home Server:
    style: row
    columns: 5
  System Monitor:
    style: row
    columns: 5
  Media Arr Stack:
    style: row
    columns: 6
